# Local settings
spring:
  config:
    activate:
      on-profile: secret
  datasource:
    url: ${datasource-url}
    username: ${datasource-username}
    password: ${datasource-password}

oauth:
  front-end-base-url: ${front-end-base-url}
  back-end-base-url: ${back-end-base-url}
  kakao:
    rest-api-key: ${kakao-rest-api-key}
  google:
    client-id: ${google-client-id}
    client-secret: ${google-client-secret}