# All profiles
spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true # live reload
---
# Local settings
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: info
---
# Development settings
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: info
---
# Production settings
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: error
