spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: jmtmonster
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop

oauth:
  back-end-base-url: http://localhost:8000
  front-end-base-url: http://localhost:3000
  kakao:
    rest-api-key: ''
  google:
    client-id: ''
    client-secret: ''

cloud:
  aws:
    credentials:
      accessKey: 'test-access-key'
      secretKey: 'test-secret-key'
    s3:
      bucket: 'test-bucket-name'
    region:
      static: us-east-1 # Error 메시지에서 해당 지역을 사용하라고 경고함.
    stack:
      auto: false
