spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: jmtmonster
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    default_batch_fetch_size: 100
  main:
    allow-bean-definition-overriding: true


oauth:
  back-end-base-url: http://localhost:8000
  front-end-base-url: http://localhost:3000
  kakao:
    rest-api-key: ''
  google:
    client-id: ''
    client-secret: ''

cloud:
  aws:
    credentials:
      accessKey: accesskey
      secretKey: secretkey
    s3:
      bucket: test-bucket-name
    region:
      static: ap-northeast-2
    stack:
      auto: false
