# Local settings
spring:
  config:
    activate:
      on-profile: secret
  datasource:
    url: ${datasource-url}
    username: ${datasource-username}
    password: ${datasource-password}

oauth:
  kakao:
    rest-api-key: ${kakao-rest-api-key}
    front-end-callback-url: ${kakao-front-end-callback-url}
    back-end-callback-url: ${kakao-back-end-callback-url}
    base-url: ${kakao-base-url}

cloud:
  aws:
    credentials:
      accessKey: ${aws-s3-access-key}
      secretKey: ${aws-s3-secret-key}
    s3:
      bucket: ${aws-s3-bucket-name}
    region:
      static: ap-northeast-2
    stack:
      auto: false